# Generated by Django 5.2 on 2025-04-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='uploads_img/')),
                ('noticia', models.TextField()),
                ('status', models.CharField(choices=[('andamento', 'Andamento'), ('realizado', 'Realizado'), ('iniciando', 'Iniciando')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
