# Generated by Django 5.2 on 2025-04-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_noticias_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='noticias',
            field=models.CharField(choices=[('politica', 'Politica'), ('esportes', 'Esportes'), ('tecnologia', 'Tecnologia')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
