# Generated by Django 5.2 on 2025-04-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_noticias_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='noticias',
            field=models.CharField(choices=[('ia', 'IA'), ('ti', 'TI'), ('games-jogos', 'Games-jogos'), ('robotica', 'Robotica')], max_length=11),
        ),
    ]
